/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mro.informática;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus Henrique
 */
public class CadastroProdutoo extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutoo
     */
    public CadastroProdutoo() {
        initComponents();
        this.populacombobox();
         jComboBox1.setEnabled(false);
        jtxtPrecoVenda.setEnabled(false);
                jtxtPrecoCusto.setEnabled(false);
                jtxNome.setEnabled(false);
                jcClasse.setEnabled(false);
    }

      public void populacombobox(){
    String sql = "SELECT *FROM fornecedor";
         Conexao con = new Conexao();
        try {
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
            jComboBox1.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutoo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtPrecoCusto = new javax.swing.JTextField();
        jtxtPrecoVenda = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jcClasse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("CÓDIGO:");

        jtxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoActionPerformed(evt);
            }
        });
        jtxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCodigoKeyPressed(evt);
            }
        });

        jLabel4.setText("PREÇO DE CUSTO:");

        jLabel5.setText("PREÇO DE VENDA:");

        jbPesquisar.setText("PESQUISAR PRODUTO");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });
        jbPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbPesquisarKeyPressed(evt);
            }
        });

        jLabel6.setText("FORNECEDOR:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jbSalvar.setText("SALVAR");
        jbSalvar.setBorder(null);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jbSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalvarKeyPressed(evt);
            }
        });

        jbExcluir.setText("EXCLUIR");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        jbExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbExcluirKeyPressed(evt);
            }
        });

        jbEditar.setText("EDITAR");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        jbEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbEditarKeyPressed(evt);
            }
        });

        jbVoltar.setText("MENU INICIAL");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        jbVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbVoltarKeyPressed(evt);
            }
        });

        jLabel1.setText("NOME DO PRODUTO:");

        jcClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teclado", "Armazenamento", "Mouse", "Áudio", "Imprensão", " ", " ", " " }));

        jButton1.setText("CONSULTA PRODUTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CLASSE DO PRODUTO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbExcluir)
                                    .addComponent(jtxtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(jbEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE))
                            .addComponent(jtxNome)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jbVoltar)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVoltar)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoActionPerformed

    private void jtxtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxtCodigo.getText());
            String sql = "SELECT * FROM produto WHERE codigo="+codigo+"";
            Conexao con = new Conexao();
            try {
                ResultSet retorno = con.sentenca.executeQuery(sql);
                if(retorno.next()){
                    JOptionPane.showMessageDialog(this, "Produto já existe produto com esse código, digite outro Código!");

                }else{
                    jtxtCodigo.setEditable(false);

                    jtxNome.setEnabled(true);
                    jcClasse.setEnabled(true);
                    jtxtPrecoVenda.setEnabled(true);
                    jtxtPrecoCusto.setEnabled(true);
                    jComboBox1.setEnabled(true);

                }
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jtxtCodigoKeyPressed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxtCodigo.getText());

        String sql = "SELECT *FROM produto WHERE codigo = "+codigo;

        Conexao con = new Conexao();
        try {
            jtxtCodigo.setEditable(false);
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
                jtxNome.setText(retorno.getString("nome"));
                jcClasse.setSelectedItem(retorno.getString("classe"));
                jComboBox1.setSelectedItem(retorno.getString("fornecedor"));
                jtxtPrecoCusto.setText(String.valueOf(retorno.getFloat("precocusto")));
                jtxtPrecoVenda.setText(String.valueOf(retorno.getFloat("precovenda")));
                jtxNome.setEnabled(true);
                jcClasse.setEnabled(true);
                jComboBox1.setEnabled(true);
                jtxtPrecoVenda.setEnabled(true);
                jtxtPrecoCusto.setEnabled(true);
            }

        } catch (SQLException ex) {
            System.out.println("Erro ao Pesquisar!"+ex.getMessage());
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbPesquisarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxtCodigo.getText());

            String sql = "SELECT *FROM produto WHERE codigo = "+codigo;

            Conexao con = new Conexao();
            try {
                jtxtCodigo.setEditable(false);
                ResultSet retorno = con.sentenca.executeQuery(sql);
                while(retorno.next()){
                    jtxNome.setText(retorno.getString("nome"));
                    jcClasse.setSelectedItem(retorno.getString("classe"));
                    jComboBox1.setSelectedItem(retorno.getString("fornecedor"));
                    jtxtPrecoCusto.setText(String.valueOf(retorno.getFloat("precocusto")));
                    jtxtPrecoVenda.setText(String.valueOf(retorno.getFloat("precovenda")));
                    jtxNome.setEnabled(true);
                    jcClasse.setEnabled(true);
                    jComboBox1.setEnabled(true);
                    jtxtPrecoVenda.setEnabled(true);
                    jtxtPrecoCusto.setEnabled(true);
                }

            } catch (SQLException ex) {
                System.out.println("Erro ao Pesquisar!"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbPesquisarKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        int codigo = Integer.parseInt(jtxtCodigo.getText());
        String nome = jtxNome.getText();
        String classe = (String) jcClasse.getSelectedItem();
        float precocusto = Float.parseFloat(jtxtPrecoCusto.getText());
        float precovenda = Float.parseFloat(jtxtPrecoVenda.getText());
        String fornecedor = (String) jComboBox1.getSelectedItem();
        String sql = "INSERT INTO produto (codigo , nome , classe ,fornecedor, precocusto, precovenda) VALUES ( "+codigo+",'"+nome+"','"+classe+"','"+fornecedor+"',"+precocusto+","+precovenda+" )";
        jtxtCodigo.setEditable(false);

        Conexao con = new Conexao();

        try {

            con.sentenca.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");

            CadastroProdutoo tela = new CadastroProdutoo();
            tela.setVisible(true);dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro!");
        }

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalvarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxtCodigo.getText());
            String nome = jtxNome.getText();
            String classe = (String) jcClasse.getSelectedItem();
            float precocusto = Float.parseFloat(jtxtPrecoCusto.getText());
            float precovenda = Float.parseFloat(jtxtPrecoVenda.getText());
            String fornecedor = (String) jComboBox1.getSelectedItem();
            String sql = "INSERT INTO produto (codigo , nome , classe ,fornecedor, precocusto, precovenda) VALUES ( "+codigo+",'"+nome+"','"+classe+"','"+fornecedor+"',"+precocusto+","+precovenda+" )";
            jtxtCodigo.setEditable(false);

            Conexao con = new Conexao();

            try {

                con.sentenca.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");

                CadastroProdutoo tela = new CadastroProdutoo();
                tela.setVisible(true);dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro no cadastro!");
            }}
    }//GEN-LAST:event_jbSalvarKeyPressed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxtCodigo.getText());
        String sql ="DELETE FROM produto WHERE codigo="+codigo;

        Conexao con = new Conexao();

        try {
            if(  con.sentenca.executeUpdate(sql)==1){
                JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
                jtxtCodigo.setText("");
                jtxNome.setText("");

                jtxtPrecoVenda.setText("");
                jtxtPrecoCusto.setText("");

                CadastroProdutoo tela = new CadastroProdutoo();
                tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        } catch (SQLException ex) {
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbExcluirKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxtCodigo.getText());
            String sql ="DELETE FROM produto WHERE codigo="+codigo;

            Conexao con = new Conexao();

            try {
                if(  con.sentenca.executeUpdate(sql)==1){
                    JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
                    jtxtCodigo.setText("");
                    jtxNome.setText("");

                    jtxtPrecoVenda.setText("");
                    jtxtPrecoCusto.setText("");

                    CadastroProdutoo tela = new CadastroProdutoo();
                    tela.setVisible(true);dispose();
                }
                else
                JOptionPane. showMessageDialog(this, "Erro ao excluir!");
            } catch (SQLException ex) {
                JOptionPane. showMessageDialog(this, "Erro ao excluir!");
            }
        }
    }//GEN-LAST:event_jbExcluirKeyPressed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxtCodigo.getText());
        String nome = jtxNome.getText();
        String classe = (String) jcClasse.getSelectedItem();
        float precocusto = Float.parseFloat(jtxtPrecoCusto.getText());
        float precovenda = Float.parseFloat(jtxtPrecoVenda.getText());
        String fornecedor = (String) jComboBox1.getSelectedItem();

        String sql ="UPDATE produto SET  nome='"+nome+"',classe='"+classe+"',fornecedor='"+fornecedor+"',precocusto='"+precocusto+"', precovenda='"+precovenda+"'WHERE codigo="+codigo+"";
        jtxtCodigo.setEditable(false);

        Conexao con = new Conexao();

        try {
            if(   con.sentenca.executeUpdate(sql)==1){
                JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
                CadastroProdutoo tela = new CadastroProdutoo();
                tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro na atualização!");
        } catch (SQLException ex) {
            System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
        }

    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbEditarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxtCodigo.getText());
            String nome = jtxNome.getText();
            String classe = (String) jcClasse.getSelectedItem();
            float precocusto = Float.parseFloat(jtxtPrecoCusto.getText());
            float precovenda = Float.parseFloat(jtxtPrecoVenda.getText());
            String fornecedor = (String) jComboBox1.getSelectedItem();

            String sql ="UPDATE produto SET  nome='"+nome+"',classe='"+classe+"',fornecedor='"+fornecedor+"',precocusto='"+precocusto+"', precovenda='"+precovenda+"'WHERE codigo="+codigo+"";
            jtxtCodigo.setEditable(false);

            Conexao con = new Conexao();

            try {
                if(   con.sentenca.executeUpdate(sql)==1){
                    JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
                    CadastroProdutoo tela = new CadastroProdutoo();
                    tela.setVisible(true);
                    dispose();}
                else
                JOptionPane. showMessageDialog(this, "Erro na atualização!");
            } catch (SQLException ex) {
                System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbEditarKeyPressed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        MenuInicial tela = new MenuInicial();
        tela.setVisible(true);
        dispose();

    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbVoltarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            MenuInicial tela = new MenuInicial();
            tela.setVisible(true);dispose();
        }
    }//GEN-LAST:event_jbVoltarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultaProduto tela = new ConsultaProduto();
        tela.setVisible(true);dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcClasse;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtPrecoCusto;
    private javax.swing.JTextField jtxtPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
