/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mro.informática;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Mateus Henrique
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        setLocationRelativeTo(null);
         jtxtNome.setEnabled(false);
                jtxtBairro.setEnabled(false);
                jtxtNumero.setEnabled(false);
                jTextField1.setEnabled(false);
                jtxtCarro.setEnabled(false);
               
                jtxtEndereco.setEnabled(false);
        
                
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbPesqusar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jtxtEndereco = new javax.swing.JTextField();
        jtxtNumero = new javax.swing.JTextField();
        jtxtBairro = new javax.swing.JTextField();
        jtxtCarro = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 120));

        jButton1.setText("MENU PRINCIPAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jbSalvar.setText("SALVAR");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jbSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalvarKeyPressed(evt);
            }
        });

        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });

        jButton4.setText("EXCLUIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jbPesqusar.setText("PESQUISAR");
        jbPesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqusarActionPerformed(evt);
            }
        });
        jbPesqusar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbPesqusarKeyPressed(evt);
            }
        });

        jLabel1.setText("CÓDIGO");

        jtxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCodigoActionPerformed(evt);
            }
        });
        jtxCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxCodigoKeyPressed(evt);
            }
        });

        jLabel2.setText("NOME:");

        jLabel3.setText("ENDEREÇO:");

        jLabel4.setText("CELULAR:");

        jLabel5.setText("NÚMERO:");

        jLabel6.setText("BAIRRO:");

        jLabel7.setText("E-MAIL:");

        jtxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNomeActionPerformed(evt);
            }
        });

        jtxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEnderecoActionPerformed(evt);
            }
        });

        jtxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumeroActionPerformed(evt);
            }
        });

        jtxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBairroActionPerformed(evt);
            }
        });

        jtxtCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarroActionPerformed(evt);
            }
        });

        try {
            jTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("CONSULTAR CLIENTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jbSalvar)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jbPesqusar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesqusar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          MenuInicial tela = new MenuInicial();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbPesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqusarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());

        String sql = "SELECT *FROM cliente WHERE codigo = "+codigo;

        Conexao con = new Conexao();
        try {
            jtxCodigo.setEditable(false);
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
                jtxtNome.setText(retorno.getString("nome"));
                jtxtBairro.setText(retorno.getString("bairro"));
                jtxtEndereco.setText(retorno.getString("endereco"));
                jTextField1.setText(retorno.getString("telefone"));
                jtxtNumero.setText(String.valueOf(retorno.getInt("numero")));
                jtxtCarro.setText(retorno.getString("email"));
              

                jtxtNome.setEnabled(true);
                jtxtBairro.setEnabled(true);
                jtxtNumero.setEnabled(true);
                jTextField1.setEnabled(true);
                jtxtCarro.setEnabled(true);
               
                jtxtEndereco.setEnabled(true);



            }
          
            
        } catch (SQLException ex) {
            System.out.println("Erro ao Pesquisar!"+ex.getMessage());
        }
    }//GEN-LAST:event_jbPesqusarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefone = jTextField1.getText();
        String carro = jtxtCarro.getText();
       

             jtxCodigo.setEditable(false);

     String sql = "INSERT INTO cliente (codigo , nome , endereco , numero , bairro, telefone, email) VALUES ( "+codigo+",'"+nome+"','"+endereco+"',"+numero+",'"+bairro+"','"+telefone+"','"+carro+"')";
     
      Conexao con = new Conexao();
    
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
          
        CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro!");
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String Endereco = jtxtEndereco.getText();
        String Bairro = jtxtBairro.getText();
        String Telefone = jTextField1.getText();
        String Carro = jtxtCarro.getText();
        

     
     String sql = "UPDATE cliente SET nome='"+nome+"', endereco = '"+Endereco+"' , numero ="+numero+" , bairro='"+Bairro+"', telefone='"+Telefone+"', email='"+Carro+"' WHERE codigo="+codigo+"";
          jtxCodigo.setEditable(false);

      Conexao con = new Conexao();
    
        try {
            if(   con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
              CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();}
            else
            JOptionPane. showMessageDialog(this, "Erro na atualização!");
        } catch (SQLException ex) {
            System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());
        String sql ="DELETE FROM cliente WHERE codigo="+codigo;

        Conexao con = new Conexao();

        try {
            if(  con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
            jtxtNome.setText("");
                jtxtBairro.setText("");
                jtxtNumero.setText("");
                jTextField1.setText("");
                jtxtCarro.setText("");
               
                jtxtEndereco.setText("");
                
                 CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        } catch (SQLException ex) {
             JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxCodigo.getText());
            String sql = "SELECT *FROM cliente WHERE codigo="+codigo+"";            
            Conexao con = new Conexao();
            try {
                ResultSet retorno = con.sentenca.executeQuery(sql);
                if(retorno.next()){
                    JOptionPane.showMessageDialog(this, "Já existe Cliente com esse código, digite outro Código!");
                    
                }else{
                         jtxCodigo.setEditable(false);

                 jtxtNome.setEnabled(true);
                jtxtBairro.setEnabled(true);
                jtxtNumero.setEnabled(true);
                jTextField1.setEnabled(true);
                jtxtCarro.setEnabled(true);
             
                jtxtEndereco.setEnabled(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jtxCodigoKeyPressed

    private void jtxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoActionPerformed

    private void jtxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNomeActionPerformed
        // TODO add your handling code here:
         jtxtEndereco.requestFocus();
    }//GEN-LAST:event_jtxtNomeActionPerformed

    private void jtxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEnderecoActionPerformed
        // TODO add your handling code here:
         jtxtNumero.requestFocus();
    }//GEN-LAST:event_jtxtEnderecoActionPerformed

    private void jtxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBairroActionPerformed
        // TODO add your handling code here:
         jTextField1.requestFocus();
    }//GEN-LAST:event_jtxtBairroActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
         jtxtCarro.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jtxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumeroActionPerformed
        // TODO add your handling code here:
        jtxtBairro.requestFocus();
    }//GEN-LAST:event_jtxtNumeroActionPerformed

    private void jbSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalvarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefone = jTextField1.getText();
        String carro = jtxtCarro.getText();
        

             jtxCodigo.setEditable(false);

     String sql = "INSERT INTO cliente (codigo , nome , endereco , numero , bairro, telefone, email) VALUES ( "+codigo+",'"+nome+"','"+endereco+"',"+numero+",'"+bairro+"','"+telefone+"','"+carro+"')";
     
      Conexao con = new Conexao();
    
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
          
        CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro!");
        }}
        
    }//GEN-LAST:event_jbSalvarKeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String Endereco = jtxtEndereco.getText();
        String Bairro = jtxtBairro.getText();
        String Telefone = jTextField1.getText();
        String Carro = jtxtCarro.getText();
        

     
     String sql = "UPDATE cliente SET nome='"+nome+"', endereco = '"+Endereco+"' , numero ="+numero+" , bairro='"+Bairro+"', telefone='"+Telefone+"', email='"+Carro+"' WHERE codigo="+codigo+"";
          jtxCodigo.setEditable(false);

      Conexao con = new Conexao();
    
        try {
            if(   con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
              CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();}
            else
            JOptionPane. showMessageDialog(this, "Erro na atualização!");
        } catch (SQLException ex) {
            System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
        }}
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyReleased

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          int codigo = Integer.parseInt(jtxCodigo.getText());
        String sql ="DELETE FROM cliente WHERE codigo="+codigo;

        Conexao con = new Conexao();

        try {
            if(  con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
            jtxtNome.setText("");
                jtxtBairro.setText("");
                jtxtNumero.setText("");
                jTextField1.setText("");
                jtxtCarro.setText("");
               
                jtxtEndereco.setText("");
                
                 CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        } catch (SQLException ex) {
             JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        }}
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        MenuInicial tela = new MenuInicial();
       tela.setVisible(true);dispose();}
          
    }//GEN-LAST:event_jButton1KeyPressed

    private void jbPesqusarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbPesqusarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         int codigo = Integer.parseInt(jtxCodigo.getText());

        String sql = "SELECT *FROM cliente WHERE codigo = "+codigo;

        Conexao con = new Conexao();
        try {
            jtxCodigo.setEditable(false);
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
                jtxtNome.setText(retorno.getString("nome"));
                jtxtBairro.setText(retorno.getString("bairro"));
                jtxtEndereco.setText(retorno.getString("endereco"));
                jTextField1.setText(retorno.getString("telefone"));
                jtxtNumero.setText(String.valueOf(retorno.getInt("numero")));
                jtxtCarro.setText(retorno.getString("email"));
              
                jtxtNome.setEnabled(true);
                jtxtBairro.setEnabled(true);
                jtxtNumero.setEnabled(true);
                jTextField1.setEnabled(true);
                jtxtCarro.setEnabled(true);
            
                jtxtEndereco.setEnabled(true);



            }
          
            
        } catch (SQLException ex) {
            System.out.println("Erro ao Pesquisar!"+ex.getMessage());
        }
        }
    }//GEN-LAST:event_jbPesqusarKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CosultaCliente tela = new CosultaCliente();
       tela.setVisible(true);dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField jTextField1;
    private javax.swing.JButton jbPesqusar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxtBairro;
    private javax.swing.JTextField jtxtCarro;
    private javax.swing.JTextField jtxtEndereco;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNumero;
    // End of variables declaration//GEN-END:variables
}
