/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mro.informática;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus Henrique
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
         jtxtNome.setEnabled(false);
         jtxtBairro.setEnabled(false);
        jtxtNumero.setEnabled(false);
        jtxtEndereco.setEnabled(false);
        telefone.setEnabled(false);
        jtxtFax.setEnabled(false);
        jtxtEstado.setEnabled(false);
        jtxtCidade.setEnabled(false);
        cnpj.setEnabled(false);
        jtxtEmail.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtxCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtCidade = new javax.swing.JTextField();
        jtxtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtFax = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 120));

        jButton1.setText("MENU PRINCIPAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("SALVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setText("EXCLUIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jButton5.setText("PESQUISAR FORNECEDOR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        jtxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCodigoActionPerformed(evt);
            }
        });
        jtxCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxCodigoKeyPressed(evt);
            }
        });

        jLabel1.setText("CÓDIGO:");

        jtxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("NOME:");

        jLabel3.setText("CNPJ:");

        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("E-MAIL:");

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("TELEFONE:");

        jLabel6.setText("ENDEREÇO:");

        jLabel7.setText("N°");

        jLabel8.setText("BAIRRO:");

        jLabel9.setText("CIDADE:");

        jLabel10.setText("ESTADO:");

        jLabel11.setText("FAX:");

        try {
            jtxtFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton6.setText("CONSULTA FORNECEDOR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addGap(95, 95, 95)
                        .addComponent(jButton3)
                        .addGap(103, 103, 103)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtxtFax))
                                            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jtxtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          MenuInicial tela = new MenuInicial();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefon = telefone.getText();
        String fax = jtxtFax.getText();
        String estado = jtxtEstado.getText();
        String cidade = jtxtCidade.getText();
        String cnp = cnpj.getText();
        String email = jtxtEmail.getText();
        
     String sql = "INSERT INTO fornecedor (codigo , nome , cnpj , email , telefone, fax, endereco, numero, bairro, cidade, estado) VALUES ( "+codigo+",'"+nome+"','"+cnp+"','"+email+"','"+telefon+"','"+fax+"','"+endereco+"',"+numero+", '"+bairro+"', '"+cidade+"','"+estado+"')";
     
      Conexao con = new Conexao();
    jtxCodigo.setEditable(false);
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
          
        CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro!");
        }
                                            

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefon = telefone.getText();
        String fax = jtxtFax.getText();
        String estado = jtxtEstado.getText();
        String cidade = jtxtCidade.getText();
        String CNPJ = cnpj.getText();
        String email = jtxtEmail.getText();
        String sql = "UPDATE fornecedor SET nome='"+nome+"',cnpj='"+CNPJ+"',email='"+email+"', telefone='"+telefon+"', fax='"+fax+"', endereco='"+endereco+"', numero="+numero+", bairro='"+bairro+"', cidade='"+cidade+"', estado='"+estado+"' WHERE codigo="+codigo+"";
     jtxCodigo.setEditable(false);
      Conexao con = new Conexao();
    
        try {
            if(   con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
              CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);
            dispose();}
            else
            JOptionPane. showMessageDialog(this, "Erro na atualização!");
        } catch (SQLException ex) {
            System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
        }
                         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());
        String sql ="DELETE FROM fornecedor WHERE codigo="+codigo;

        Conexao con = new Conexao();

        try {
            if(  con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
            jtxtNome.setText("");
                jtxtBairro.setText("");
                jtxtNumero.setText("");
                jtxtEndereco.setText("");
                jtxCodigo.setText("");
        telefone.setText("");
        jtxtFax.setText("");
        jtxtEstado.setText("");
        jtxtCidade.setText("");
        cnpj.setText("");
        jtxtEmail.setText("");
                 CadastroFornecedor tela = new CadastroFornecedor();
       tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        } catch (SQLException ex) {
             JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(jtxCodigo.getText());
            String sql = "SELECT *FROM fornecedor WHERE codigo="+codigo+"";            
            Conexao con = new Conexao();
            try {
                ResultSet retorno = con.sentenca.executeQuery(sql);
                if(retorno.next()){
                    JOptionPane.showMessageDialog(this, "Já existe Cliente com esse código, digite outro Código!");
                    
                }else{
                 jtxCodigo.setEditable(false);
                 jtxtNome.setEnabled(true);
                jtxtBairro.setEnabled(true);
                jtxtNumero.setEnabled(true);
                jtxtEndereco.setEnabled(true);
                
        telefone.setEnabled(true);
        jtxtFax.setEnabled(true);
        jtxtEstado.setEnabled(true);
        jtxtCidade.setEnabled(true);
        cnpj.setEnabled(true);
        jtxtEmail.setEnabled(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtxCodigoKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCodigo.getText());

        String sql = "SELECT *FROM fornecedor WHERE codigo = "+codigo;

        Conexao con = new Conexao();
        jtxCodigo.setEditable(false);
        try {
            
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
                jtxtNome.setText(retorno.getString("nome"));
                jtxtBairro.setText(retorno.getString("bairro"));
                jtxtEndereco.setText(retorno.getString("endereco"));
                jtxtFax.setText(retorno.getString("fax"));
                jtxtNumero.setText(String.valueOf(retorno.getInt("numero")));
                jtxtEstado.setText(retorno.getString("estado"));
               cnpj.setText(retorno.getString("cnpj"));
               jtxtEmail.setText(retorno.getString("email"));
               jtxtCidade.setText(retorno.getString("cidade"));
               telefone.setText(retorno.getString("telefone"));
               
               jtxtNome.setEnabled(true);
                jtxtBairro.setEnabled(true);
                jtxtNumero.setEnabled(true);
                jtxtEndereco.setEnabled(true);
                
        telefone.setEnabled(true);
        jtxtFax.setEnabled(true);
        jtxtEstado.setEnabled(true);
        jtxtCidade.setEnabled(true);
        cnpj.setEnabled(true);
        jtxtEmail.setEnabled(true);
                



            }
          
            
        } catch (SQLException ex) {
            System.out.println("Erro ao Pesquisar!"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         MenuInicial tela = new MenuInicial();
       tela.setVisible(true);dispose();
        
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefon = telefone.getText();
        String fax = jtxtFax.getText();
        String estado = jtxtEstado.getText();
        String cidade = jtxtCidade.getText();
        String cnp = cnpj.getText();
        String email = jtxtEmail.getText();
        
     String sql = "INSERT INTO fornecedor (codigo , nome , cnpj , email , telefone, fax, endereco, numero, bairro, cidade, estado) VALUES ( "+codigo+",'"+nome+"','"+cnp+"','"+email+"','"+telefon+"','"+fax+"','"+endereco+"',"+numero+", '"+bairro+"', '"+cidade+"','"+estado+"')";
     
      Conexao con = new Conexao();
    jtxCodigo.setEditable(false);
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
          
        CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no cadastro!");
        }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        int codigo = Integer.parseInt(jtxCodigo.getText());
        int numero = Integer.parseInt(jtxtNumero.getText());
        String nome = jtxtNome.getText();
        String endereco = jtxtEndereco.getText();
        String bairro = jtxtBairro.getText();
        String telefon = telefone.getText();
        String fax = jtxtFax.getText();
        String estado = jtxtEstado.getText();
        String cidade = jtxtCidade.getText();
        String CNPJ = cnpj.getText();
        String email = jtxtEmail.getText();
        String sql = "UPDATE fornecedor SET nome='"+nome+"',cnpj='"+CNPJ+"',email='"+email+"', telefone='"+telefon+"', fax='"+fax+"', endereco='"+endereco+"', numero="+numero+", bairro='"+bairro+"', cidade='"+cidade+"', estado='"+estado+"' WHERE codigo="+codigo+"";
     jtxCodigo.setEditable(false);
      Conexao con = new Conexao();
    
        try {
            if(   con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Atualizado com sucesso!");
              CadastroCliente tela = new CadastroCliente();
       tela.setVisible(true);
            dispose();}
            else
            JOptionPane. showMessageDialog(this, "Erro na atualização!");
        } catch (SQLException ex) {
            System.out.println("Erro na sentença UPDATE!"+ex.getMessage());
        }
                         
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         int codigo = Integer.parseInt(jtxCodigo.getText());
        String sql ="DELETE FROM fornecedor WHERE codigo="+codigo;

        Conexao con = new Conexao();

        try {
            if(  con.sentenca.executeUpdate(sql)==1){
            JOptionPane. showMessageDialog(this, "Deletado com sucesso!");
            jtxtNome.setText("");
                jtxtBairro.setText("");
                jtxtNumero.setText("");
                jtxtEndereco.setText("");
                jtxCodigo.setText("");
        telefone.setText("");
        jtxtFax.setText("");
        jtxtEstado.setText("");
        jtxtCidade.setText("");
        cnpj.setText("");
        jtxtEmail.setText("");
                 CadastroFornecedor tela = new CadastroFornecedor();
       tela.setVisible(true);dispose();
            }
            else
            JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        } catch (SQLException ex) {
             JOptionPane. showMessageDialog(this, "Erro ao excluir!");
        }
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         MenuInicial tela = new MenuInicial();
       tela.setVisible(true);
       dispose();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ConsultaFornecedor tela = new ConsultaFornecedor();
       tela.setVisible(true);dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxtBairro;
    private javax.swing.JTextField jtxtCidade;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEndereco;
    private javax.swing.JTextField jtxtEstado;
    private javax.swing.JFormattedTextField jtxtFax;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNumero;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
