/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mro.informática;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mateus Henrique
 */
public class Vendas extends javax.swing.JFrame {
    Conexao con = new Conexao();
   
    
    
    
    
     
    public Vendas() {
        initComponents();
        this.populacombobox();
      setLocationRelativeTo(null);
        SimpleDateFormat format = new SimpleDateFormat( "dd/MM/yyyy" );  
  
jtxtData.setText( format.format( new Date() ) ); 
        jtxtData.setEditable(false);
      
    }
    public void populacombobox(){
    String sql = "SELECT *FROM cliente";
         Conexao con = new Conexao();
        try {
            ResultSet retorno = con.sentenca.executeQuery(sql);
            while(retorno.next()){
            jComboBox1.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutoo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private DefaultTableModel tabela;
   private DefaultTableModel tabela1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableVendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxValor = new javax.swing.JTextField();
        jtxQuantidade = new javax.swing.JTextField();
        jbFinalizar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableProduto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtProduto = new javax.swing.JTextField();
        jtxtnome_produto = new javax.swing.JTextField();
        jtxtTotalVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigovenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setLocation(new java.awt.Point(0, 0));

        jtableVendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableVendas);

        jLabel1.setText("VENDAS:");

        jtxTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxTotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("VALOR TOTAL DA VENDA: ");

        jLabel3.setText("QUANTIDADE:");

        jLabel4.setText("VALOR DO PRODUTO:");

        jtxValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxValorActionPerformed(evt);
            }
        });

        jtxQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxQuantidadeFocusGained(evt);
            }
        });
        jtxQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxQuantidadeActionPerformed(evt);
            }
        });

        jbFinalizar.setText("FINALIZAR E IMPRIMIR");
        jbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarActionPerformed(evt);
            }
        });

        jbCancelar.setText("CANCELAR VENDA");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbMenu.setText("MENU PRINCIPAL");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        jtableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtableProduto);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("ADICIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel5.setText("DATA:");

        jtxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDataActionPerformed(evt);
            }
        });

        jLabel6.setText("PRODUTO: ");

        jtxtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtProdutoActionPerformed(evt);
            }
        });

        jtxtnome_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnome_produtoActionPerformed(evt);
            }
        });
        jtxtnome_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnome_produtoKeyReleased(evt);
            }
        });

        jtxtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalVendaActionPerformed(evt);
            }
        });

        jLabel7.setText("TOTAL PRODUTO:");

        jLabel8.setText("CÓDIGO VENDA:");

        codigovenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigovendaActionPerformed(evt);
            }
        });
        codigovenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigovendaKeyPressed(evt);
            }
        });

        jLabel9.setText("PRODUTOS:");

        jLabel10.setText("PESQUISA:");

        jComboBox1.setMaximumRowCount(500);

        jLabel11.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jbFinalizar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addGap(60, 60, 60)
                                .addComponent(jbMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtnome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addComponent(jtxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(codigovenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jtxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFinalizar)
                    .addComponent(jbCancelar)
                    .addComponent(jbMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxQuantidadeActionPerformed
        // TODO add your handling code here:
        jButton1.requestFocus();
        
    }//GEN-LAST:event_jtxQuantidadeActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Venda Cancelada!");
         Vendas tela = new Vendas();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        // TODO add your handling code here:
         MenuInicial tela = new MenuInicial();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jbMenuActionPerformed

    private void jtxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDataActionPerformed
        // TODO add your handling code here:
   jtxtnome_produto.requestFocus();
    }//GEN-LAST:event_jtxtDataActionPerformed

    private void jtxTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxTotalActionPerformed

    private void jtableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableProdutoMouseClicked
        // TODO add your handling code here:
        String nomeproduto = ""+ jtableProduto.getValueAt( jtableProduto.getSelectedRow(),1);
        String preco_produto = ""+ jtableProduto.getValueAt( jtableProduto.getSelectedRow(),2);
        jtxValor.setText(preco_produto);
        jtxtProduto.setText(nomeproduto);
        jtxQuantidade.setText("1");
        jtxValor.setEditable(false);
            jtxTotal.setEditable(false);
       
    }//GEN-LAST:event_jtableProdutoMouseClicked

    private void jtxtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtProdutoActionPerformed

    private void jtxQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxQuantidadeFocusGained
        // TODO add your handling code here:
        float valortotal;
        valortotal=Float.parseFloat(jtxValor.getText())*Integer.parseInt(jtxQuantidade.getText());
        jtxTotal.setText(String.valueOf(valortotal));
    }//GEN-LAST:event_jtxQuantidadeFocusGained

    private void jtxValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxValorActionPerformed

    private void jtxtnome_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnome_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnome_produtoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       
        float valortotal=Float.parseFloat(jtxValor.getText())*Integer.parseInt(jtxQuantidade.getText());
        jtxTotal.setText(String.valueOf(valortotal));
        String nome = jtxtProduto.getText();
         String cliente = (String) jComboBox1.getSelectedItem();
        int quant = Integer.parseInt(jtxQuantidade.getText());
        float valor=Float.parseFloat(jtxValor.getText());
          int codigo = Integer.parseInt(codigovenda.getText());

        
         String sql = "INSERT INTO vendas (codigovenda, nome, qtd, precovenda, total, cliente) VALUES ('"+codigo+"','"+nome+"',"+quant+", "+valor+", "+valortotal+", '"+cliente+"')";
        codigovenda.setEditable(false);
       jtxValor.setEditable(false);
            jtxTotal.setEditable(false);
       Conexao con = new Conexao();
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, " Inserido com sucesso!");
          
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Inserir!");
            
        }
               this.tabela();
       
     
     
    }//GEN-LAST:event_jButton1ActionPerformed
public void tabela(){
    int codigo = Integer.parseInt(codigovenda.getText());
 String sqll = "SELECT *FROM vendas WHERE codigovenda like'%"+codigo+"%'";
      DefaultTableModel val = new DefaultTableModel(new Object[]{"Produto","Quantidade", "Preço Unitário R$", "Preço Total R$"},0);
Conexao con = new Conexao();
       
        try {
            ResultSet retorno = con.sentenca.executeQuery(sqll);
            while(retorno.next()){
                
                String nom = retorno.getString("nome");
                String quan = retorno.getString("qtd");
                String precovenda = retorno.getString("precovenda");
                String total=retorno.getString("total");
                  val.addRow(new String[] { nom,quan ,precovenda, total});
                  

            }
            jtableVendas.setModel(val);
            soma();
            jtxValor.setEditable(false);
            jtxTotal.setEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void soma(){
        float totalvendido=0;
        Conexao con = new Conexao();
        int codigo = Integer.parseInt(codigovenda.getText());
        String sqll = "SELECT total FROM vendas WHERE codigovenda ="+codigo;
        
        try {
            ResultSet retorno = con.sentenca.executeQuery(sqll);
            while(retorno.next()){
                
            totalvendido=totalvendido+retorno.getFloat("total");
            }jtxtTotalVenda.setText(String.valueOf(totalvendido));
            
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Venda Finalizada com Sucesso");
        tabela = (DefaultTableModel)jtableVendas.getModel();
        tabela.setNumRows(0);
        tabela1 = (DefaultTableModel)jtableProduto.getModel();
        tabela1.setNumRows(0);
        
        Vendas tela = new Vendas();
       tela.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_jbFinalizarActionPerformed

    private void jtxtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalVendaActionPerformed
        // TODO add your handling code here:
      
                
    }//GEN-LAST:event_jtxtTotalVendaActionPerformed

    private void codigovendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigovendaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int codigo = Integer.parseInt(codigovenda.getText());
            String sql = "SELECT * FROM vendas WHERE codigovenda="+codigo;            
            Conexao con = new Conexao();
            try {
                ResultSet retorno = con.sentenca.executeQuery(sql);
                if(retorno.next()){
                    JOptionPane.showMessageDialog(this, "Produto já existe produto com esse código, digite outro Código!");
                    
                }else{
                         codigovenda.setEditable(false);

                
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_codigovendaKeyPressed

    private void codigovendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigovendaActionPerformed
        // TODO add your handling code here:
        jtxQuantidade.requestFocus();
    }//GEN-LAST:event_codigovendaActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         float valortotal=Float.parseFloat(jtxValor.getText())*Integer.parseInt(jtxQuantidade.getText());
        jtxTotal.setText(String.valueOf(valortotal));
         String cliente = (String) jComboBox1.getSelectedItem();
        String nome = jtxtProduto.getText();
        int quant = Integer.parseInt(jtxQuantidade.getText());
        float valor=Float.parseFloat(jtxValor.getText());
          int codigo = Integer.parseInt(codigovenda.getText());
          String data = jtxtData.getText();
        
         String sql = "INSERT INTO vendas (data, codigovenda, nome, qtd, precovenda, total, cliente) VALUES ('"+data+"','"+codigo+"','"+nome+"',"+quant+", "+valor+", "+valortotal+", '"+cliente+"')";
        codigovenda.setEditable(false);
       jtxValor.setEditable(false);
            jtxTotal.setEditable(false);
       Conexao con = new Conexao();
        try {
           
                con.sentenca.executeUpdate(sql); 
            
            JOptionPane.showMessageDialog(this, " Inserido com sucesso!");
          
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Inserir!");
            
        }
               this.tabela();
        }
       
    }//GEN-LAST:event_jButton1KeyPressed

    private void jtxtnome_produtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnome_produtoKeyReleased
        // TODO add your handling code here: String sql = "SELECT codigo, nome, precovenda FROM produto WHERE nome like'%"+jtxtnome_produto.getText()+"%'";
        String sql = "SELECT codigo, nome, precovenda FROM produto WHERE nome like'%"+jtxtnome_produto.getText()+"%'";
        DefaultTableModel val = new DefaultTableModel(new Object[]{"Código", "Produto", "Preço R$"},0);
       
       Conexao con = new Conexao();
        try {
            ResultSet retorno = con.sentenca.executeQuery(sql);
           
            if(retorno.next()){
                
                String codigo = retorno.getString("codigo");
                String nome = retorno.getString("nome");
                String precovenda = retorno.getString("precovenda");
                  val.addRow(new String[] {codigo, nome, precovenda});
            }
            
            jtableProduto.setModel(val);
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jtxtnome_produtoKeyReleased
  
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigovenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JTable jtableProduto;
    private javax.swing.JTable jtableVendas;
    private javax.swing.JTextField jtxQuantidade;
    private javax.swing.JTextField jtxTotal;
    private javax.swing.JTextField jtxValor;
    private javax.swing.JFormattedTextField jtxtData;
    private javax.swing.JTextField jtxtProduto;
    private javax.swing.JTextField jtxtTotalVenda;
    private javax.swing.JTextField jtxtnome_produto;
    // End of variables declaration//GEN-END:variables
}
